### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by drieks**
Hi,

I added a note to README.md that kastree is currently not being actively developed.

### CODE REVIEW

**Comment by cretz** [comment]
Can you place it below the feature set (and maybe that little paragraph after that)...in bold is just fine and link to your project is fine too, just don't really want "Note" to be the main markdown heading.

**Comment by drieks** [comment]
Thank you @cretz, I moved the text down.

BTW: Do you know other AST parsing libraries for kotlin?

The main reason for starting `kotlinx.ast` was for me that it is not possible to use `kastree` on JS or Native and I don't find another easy way..

**Comment by cretz** [comment]
> Do you know other AST parsing libraries for kotlin?

I do not

> The main reason for starting kotlinx.ast was for me that it is not possible to use kastree on JS or Native and I don't find another easy way..

I specifically separated out the AST project from the parsing project for this reason. The features such as the immutable AST, the writer, visitors, etc are specifically written to be able to be used from all platforms. My initial use case was to hand-build AST and I didn't need a parser.

**Comment by drieks** [comment]
My use case is parsing the AST into data classes and then generating other source files based on the parsed structure (using kotlinpoet).

Can you tell me the use case for "read, transform and write"? A source code linter?

**Pull request merged**
